set nocompatible
syntax on
filetype plugin indent on

set number
if has("relativenumber")
    set relativenumber
endif
set hlsearch
set incsearch
set visualbell

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set nobackup
set nowritebackup
set noswapfile

if has('persistent_undo')
    set undofile
    set undodir=~/.vimundodir
endif

if has('clipboard')
    set clipboard=unnamed,unnamedplus
endif

if has("gui_running")
    set guifont=Terminess\ Nerd\ Font\ Mono:h12
    set lines=35
    set columns=110
endif

if has("termguicolors")
    set termguicolors
endif

if has("win32") || has("win64")
    set shell=powershell.exe
endif

let mapleader = ' '

nmap <C-s> :up<CR>
